# Generated by Django 3.0.5 on 2020-04-20 05:09

from django.db import migrations, models
import task_reporter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doer', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reports', models.CharField(choices=[('d', 'DAILY'), ('w', 'WEEKLY'), ('m', 'MONTHLY')], max_length=50)),
                ('team_lead', models.CharField(max_length=50)),
                ('no_of_hours', models.IntegerField()),
                ('today_progress', models.TextField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Ranjan', 'Amitesh Ranjan'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika'), ('Ajeet', 'Ajeet'), ('Shekhar', 'Shekhar')])),
                ('today_doc', models.FileField(upload_to=task_reporter.models.user_directory_path)),
                ('concerns', models.TextField()),
                ('next_plan', models.TextField()),
                ('next_plan_doc', models.FileField(upload_to=task_reporter.models.user_directory_path)),
            ],
        ),
    ]
