# Generated by Django 3.0.5 on 2020-04-20 06:19

from django.db import migrations, models
import task_reporter.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reporter', '0002_auto_20200420_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='doer',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='progress',
            name='next_plans_document',
            field=models.FileField(blank=True, upload_to=task_reporter.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='progress',
            name='team_lead',
            field=models.TextField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Ranjan', 'Amitesh Ranjan'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika'), ('Ajeet', 'Ajeet'), ('Shekhar', 'Shekhar')]),
        ),
        migrations.AlterField(
            model_name='progress',
            name='today_document',
            field=models.FileField(blank=True, upload_to=task_reporter.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='progress',
            name='today_progress',
            field=models.CharField(max_length=50),
        ),
    ]
