# Generated by Django 3.0.5 on 2020-04-20 13:25

from django.db import migrations, models
import task_reporter.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_reporter', '0003_auto_20200420_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='next_plans_document',
            field=models.FileField(upload_to=task_reporter.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='progress',
            name='today_document',
            field=models.FileField(upload_to=task_reporter.models.user_directory_path),
        ),
    ]
